
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ./challenges:/app/challenges
    environment:
      - PORT=8080

  code-runner:
    build:
      context: .
      dockerfile: docker/Dockerfile.runner
    volumes:
      - code-runner-data:/code
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

volumes:
  code-runner-data: