services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./challenges:/app/challenges
      - executor-workdir:/app/executor-workdir
      - /var/run/docker.sock:/var/run/docker.sock

  runner:
    build:
      context: .
      dockerfile: docker/Dockerfile.runner
    image: code-challenge-runner
    profiles:
      - donotstart

volumes:
  executor-workdir: