version: '3.8'

services:
  app:
    image: strathlearn-app:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - challenge-data:/app/backend/challenges
    environment:
      - PORT=8080
    depends_on:
      - redis
    networks:
      - strathlearn-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - strathlearn-network

volumes:
  challenge-data:
  redis-data:
  code-runner-data:
    external: true

networks:
  strathlearn-network:
    driver: bridge
