FROM golang:1.21-alpine

WORKDIR /app

COPY backend/go.mod ./
COPY backend/go.sum ./
RUN go mod download
RUN go get github.com/google/uuid

COPY . .

# Install Docker client
RUN apk add --no-cache docker-cli

RUN apk add --no-cache gcc musl-dev
RUN go build -o app backend/main.go

EXPOSE 8080

CMD ["./app"]