name: Build and Test Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build runner image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile.runner
        tags: code-challenge-runner:latest
        push: false
        load: true
        
    - name: Build server image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile.server
        tags: strathlearn-server:latest
        push: false
        load: true
        
    - name: Test containers
      run: |
        docker images
      